CREATE TABLE navsteva (id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, zakaznik_id INT(11) NOT NULL, prichod TIMESTAMP DEFAULT CURRENT_TIMESTAMP, odchod TIMESTAMP NULL DEFAULT NULL, id_kluca INT(11));
CREATE TABLE udalost (id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, zakaznik_id INT(11) NOT NULL, datum TIMESTAMP DEFAULT CURRENT_TIMESTAMP, typ VARCHAR(32) NOT NULL, obsah TEXT);
