package sk.upjs.ics.paz1c.fitnesscentrum;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class ZoznamZakaznikovForm extends javax.swing.JFrame {

    private ZakaznikTableModel zakaznikTableModel;
    private PritomniZakazniciTableModel pritomniZakazniciTableModel;
    /**
     * Creates new form ZoznamZakaznikovForm
     */
    public ZoznamZakaznikovForm() {
        zakaznikTableModel = new ZakaznikTableModel();
        pritomniZakazniciTableModel = new PritomniZakazniciTableModel();
        initComponents();
        inicializaciaZaciatocnehoStavu();  
        aktualizovatZoznamZakaznikov();
    }

    public void aktualizovatZoznamZakaznikov() {
        ZakaznikTableModel model = (ZakaznikTableModel) zoznamZakaznikovTable.getModel();
        model.aktualizovat();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zoznamVsetkychPane = new javax.swing.JTabbedPane();
        pritomniScrollPane = new javax.swing.JScrollPane();
        pritomniTable = new javax.swing.JTable();
        zoznamZakaznikovScrollPane = new javax.swing.JScrollPane();
        zoznamZakaznikovTable = new javax.swing.JTable();
        pridatZakaznikButton = new javax.swing.JButton();
        odstranZakaznikaButton = new javax.swing.JButton();
        zakaznikLabel = new javax.swing.JLabel();
        prichodButton = new javax.swing.JButton();
        odchodButton = new javax.swing.JButton();
        recepcnyLabel = new javax.swing.JLabel();
        pridatRecepcnehoButton = new javax.swing.JButton();
        odstranRecepcnehoButton = new javax.swing.JButton();
        zmenaUdajovRecepcnyButton = new javax.swing.JButton();
        odhlasenieButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fitnesscentrum");
        setName("zoznamZakaznikovFrame"); // NOI18N

        pritomniTable.setModel(new PritomniZakazniciTableModel()
        );
        pritomniScrollPane.setViewportView(pritomniTable);

        zoznamVsetkychPane.addTab("Pritomni", pritomniScrollPane);

        zoznamZakaznikovTable.setModel(new ZakaznikTableModel());
        zoznamZakaznikovScrollPane.setViewportView(zoznamZakaznikovTable);

        zoznamVsetkychPane.addTab("Zoznam", zoznamZakaznikovScrollPane);

        pridatZakaznikButton.setText("Pridať");
        pridatZakaznikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatZakaznikButtonActionPerformed(evt);
            }
        });

        odstranZakaznikaButton.setText("Odstráň");
        odstranZakaznikaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odstranZakaznikaButtonActionPerformed(evt);
            }
        });

        zakaznikLabel.setText("Zákazník");

        prichodButton.setText("Príchod");
        prichodButton.setEnabled(false);
        prichodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prichodButtonActionPerformed(evt);
            }
        });

        odchodButton.setText("Odchod");
        odchodButton.setEnabled(false);
        odchodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odchodButtonActionPerformed(evt);
            }
        });

        recepcnyLabel.setText("Recepčný");

        pridatRecepcnehoButton.setText("Pridať");
        pridatRecepcnehoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatRecepcnehoButtonActionPerformed(evt);
            }
        });

        odstranRecepcnehoButton.setText("Odstráň");
        odstranRecepcnehoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odstranRecepcnehoButtonActionPerformed(evt);
            }
        });

        zmenaUdajovRecepcnyButton.setText("Zmena údajov");
        zmenaUdajovRecepcnyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmenaUdajovRecepcnyButtonActionPerformed(evt);
            }
        });

        odhlasenieButton.setText("Odhlásenie");
        odhlasenieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odhlasenieButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(zoznamVsetkychPane, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(zakaznikLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(recepcnyLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(pridatRecepcnehoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(odstranRecepcnehoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prichodButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(pridatZakaznikButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(odstranZakaznikaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(odchodButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(odhlasenieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zmenaUdajovRecepcnyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zoznamVsetkychPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(zakaznikLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pridatZakaznikButton)
                    .addComponent(odstranZakaznikaButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prichodButton)
                    .addComponent(odchodButton))
                .addGap(138, 138, 138)
                .addComponent(recepcnyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(odstranRecepcnehoButton)
                    .addComponent(pridatRecepcnehoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zmenaUdajovRecepcnyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(odhlasenieButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridatZakaznikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatZakaznikButtonActionPerformed
        new NovyZakaznikForm(this).setVisible(true);

    }//GEN-LAST:event_pridatZakaznikButtonActionPerformed

    private void odstranZakaznikaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odstranZakaznikaButtonActionPerformed
        int idZakaznika = (Integer)zakaznikTableModel.getValueAt(this.zoznamZakaznikovTable.getSelectedRow(),7);

        DaoFactory.INSTANCE.getMySQLZakaznikDao().vymazZakaznika(idZakaznika);
        aktualizovatZoznamZakaznikov();
        //tu moze byt toto nizsie ale v tom pripade tam bude zobrazeny stale ale nebude pristupny, az po kliknuti na zakaznika
        //vymazZakaznikaButton.setEnabled(false);
        odstranZakaznikaButton.setVisible(false);
        odchodButton.setVisible(false);
        prichodButton.setVisible(false); 
    }//GEN-LAST:event_odstranZakaznikaButtonActionPerformed

    private void odchodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odchodButtonActionPerformed
        int idZakaznika = (Integer) pritomniTable.getValueAt(pritomniTable.getSelectedRow(),4);
        odchodButton.setVisible(false);
    }//GEN-LAST:event_odchodButtonActionPerformed

    private void prichodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prichodButtonActionPerformed
        int idZakaznika = (Integer)zakaznikTableModel.getValueAt(this.zoznamZakaznikovTable.getSelectedRow(),7);
        DaoFactory.INSTANCE.getMySQLZakaznikDao().prichod(idZakaznika, WIDTH);
        aktualizovatZoznamZakaznikov();
        prichodButton.setVisible(false);
    }//GEN-LAST:event_prichodButtonActionPerformed

    private void pridatRecepcnehoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatRecepcnehoButtonActionPerformed
        new NovyRecepcnyForm().setVisible(true);
    }//GEN-LAST:event_pridatRecepcnehoButtonActionPerformed

    private void odhlasenieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odhlasenieButtonActionPerformed
        this.dispose();
        new PrihlasovanieForm().setVisible(true);
    }//GEN-LAST:event_odhlasenieButtonActionPerformed

    private void odstranRecepcnehoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odstranRecepcnehoButtonActionPerformed
     
    }//GEN-LAST:event_odstranRecepcnehoButtonActionPerformed

    private void zmenaUdajovRecepcnyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmenaUdajovRecepcnyButtonActionPerformed
        //zatial menim recepcneho s id 1
        new ZmenaUdajovRecepcnehoForm(1).setVisible(true);
    }//GEN-LAST:event_zmenaUdajovRecepcnyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZoznamZakaznikovForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZoznamZakaznikovForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZoznamZakaznikovForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZoznamZakaznikovForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrihlasovanieForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton odchodButton;
    private javax.swing.JButton odhlasenieButton;
    private javax.swing.JButton odstranRecepcnehoButton;
    private javax.swing.JButton odstranZakaznikaButton;
    private javax.swing.JButton prichodButton;
    private javax.swing.JButton pridatRecepcnehoButton;
    private javax.swing.JButton pridatZakaznikButton;
    private javax.swing.JScrollPane pritomniScrollPane;
    private javax.swing.JTable pritomniTable;
    private javax.swing.JLabel recepcnyLabel;
    private javax.swing.JLabel zakaznikLabel;
    private javax.swing.JButton zmenaUdajovRecepcnyButton;
    private javax.swing.JTabbedPane zoznamVsetkychPane;
    private javax.swing.JScrollPane zoznamZakaznikovScrollPane;
    private javax.swing.JTable zoznamZakaznikovTable;
    // End of variables declaration//GEN-END:variables

    private void inicializaciaZaciatocnehoStavu() {
        //tu moze byt aj toto nizsie ale v tom pripade tam bude zobrazeny stale ale nebude pristupny, az po kliknuti na zakaznika
        //vymazZakaznikaButton.setEnabled(false);
        odstranZakaznikaButton.setVisible(false);
        odchodButton.setVisible(false);
        prichodButton.setVisible(false);
        pritomniTable.setModel(pritomniZakazniciTableModel);

        pritomniTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                odchodButton.setVisible(true);    
            }
        });
        //po kliknuti na riadok v tabulke sa zavola metoda valueChange v nasom ListSelectionListeneri
        zoznamZakaznikovTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                //tu moze byt aj toto nizsie ale v tom pripade tam bude zobrazeny stale ale nebude pristupny, az po kliknuti na zakaznika
                //vymazZakaznikaButton.setEnabled(true);
                odstranZakaznikaButton.setVisible(true);
                odchodButton.setVisible(true);
                prichodButton.setVisible(true);
            }
        });
    }
}