package sk.upjs.ics.paz1c.fitnesscentrum.form;

import javax.swing.JOptionPane;
import sk.upjs.ics.paz1c.fitnesscentrum.ObjectFactory;
import sk.upjs.ics.paz1c.fitnesscentrum.ZakaznikTableModel;
import sk.upjs.ics.paz1c.fitnesscentrum.dao.ZakaznikDao;
import sk.upjs.ics.paz1c.fitnesscentrum.entity.Zakaznik;

public class PrichodJednorazovyForm extends javax.swing.JDialog {

    private final ZakaznikDao zakaznikDao = ObjectFactory.INSTANCE.getZakaznikDao();
    private static final int ID_COLUMN = 5;

    /**
     * Creates new form PrichodJednorazovyForm
     * @param parent
     * @param modal
     */
    public PrichodJednorazovyForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        aktualizovatZoznamZakaznikov();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hladatPodlaMenaLabel = new javax.swing.JLabel();
        hladatPodlaMenaTextField = new javax.swing.JTextField();
        hladatButton = new javax.swing.JButton();
        zoznamZakaznikovScrollPane = new javax.swing.JScrollPane();
        zoznamZakaznikovTable = new javax.swing.JTable();
        prichodButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jednorázový príchod");

        hladatPodlaMenaLabel.setText("Hľadať podľa mena: ");

        hladatButton.setText("Hľadať");
        hladatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hladatButtonActionPerformed(evt);
            }
        });

        zoznamZakaznikovTable.setModel(new ZakaznikTableModel(""));
        zoznamZakaznikovScrollPane.setViewportView(zoznamZakaznikovTable);

        prichodButton.setText("Príchod");
        prichodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prichodButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zoznamZakaznikovScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hladatPodlaMenaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hladatPodlaMenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hladatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prichodButton, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hladatPodlaMenaLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hladatPodlaMenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hladatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prichodButton)))
                .addGap(18, 18, 18)
                .addComponent(zoznamZakaznikovScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prichodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prichodButtonActionPerformed
        try {
            Long idZakaznika = (Long) zoznamZakaznikovTable.getModel().getValueAt(this.zoznamZakaznikovTable.getSelectedRow(), ID_COLUMN);
            Zakaznik zakaznik = zakaznikDao.dajZakaznikaSId(idZakaznika);
            if (!zakaznik.isPritomny()) {
                new PotvrditPrichodZakaznikaForm(this, true, zakaznik).setVisible(true);
                aktualizovatZoznamZakaznikov();
            } else {
                JOptionPane.showMessageDialog(this, "Zákazník je už prítomný!");
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Vyber zákazníka na príchod.");
        }
    }//GEN-LAST:event_prichodButtonActionPerformed

    private void hladatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hladatButtonActionPerformed
        zoznamZakaznikovTable.setModel(new ZakaznikTableModel(hladatPodlaMenaTextField.getText()));
    }//GEN-LAST:event_hladatButtonActionPerformed

    public void aktualizovatZoznamZakaznikov() {
        ZakaznikTableModel model = (ZakaznikTableModel) zoznamZakaznikovTable.getModel();
        model.aktualizovat();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hladatButton;
    private javax.swing.JLabel hladatPodlaMenaLabel;
    private javax.swing.JTextField hladatPodlaMenaTextField;
    private javax.swing.JButton prichodButton;
    private javax.swing.JScrollPane zoznamZakaznikovScrollPane;
    private javax.swing.JTable zoznamZakaznikovTable;
    // End of variables declaration//GEN-END:variables
}
