package sk.upjs.ics.paz1c.fitnesscentrum.form;

import javax.swing.JOptionPane;
import sk.upjs.ics.paz1c.fitnesscentrum.ObjectFactory;
import sk.upjs.ics.paz1c.fitnesscentrum.manager.ZakaznikManager;
import sk.upjs.ics.paz1c.fitnesscentrum.model.KlucComboBoxModel;
import sk.upjs.ics.paz1c.fitnesscentrum.entity.Kluc;
import sk.upjs.ics.paz1c.fitnesscentrum.entity.Zakaznik;
import sk.upjs.ics.paz1c.fitnesscentrum.exception.NedostatocnyKreditException;
import sk.upjs.ics.paz1c.fitnesscentrum.exception.NeexistujuciZakaznikException;

public class PrichodPermanentkouForm extends javax.swing.JDialog {

    private final ZakaznikManager zakaznikManager = ObjectFactory.INSTANCE.getZakaznikManager();
    private Zakaznik zakaznik;

    /**
     * Creates new form PrichodKartouForm
     *
     * @param parent
     * @param modal
     */
    public PrichodPermanentkouForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menoLabel = new javax.swing.JLabel();
        zobrazMenoLabel = new javax.swing.JLabel();
        klucLabel = new javax.swing.JLabel();
        klucComboBox = new javax.swing.JComboBox<>();
        prichodButton = new javax.swing.JButton();
        kreditLabel = new javax.swing.JLabel();
        cisloKartyLabel = new javax.swing.JLabel();
        zobrazCisloKartyLabel = new javax.swing.JLabel();
        zobrazKreditLabel = new javax.swing.JLabel();
        cisloKartyTextField = new javax.swing.JTextField();
        zadatCisloLabel = new javax.swing.JLabel();
        nacitatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Príchod permanentkou");
        setResizable(false);

        menoLabel.setText("Meno: ");

        klucLabel.setText("Kľúč: ");

        klucComboBox.setModel(new KlucComboBoxModel());
        klucComboBox.setEnabled(false);

        prichodButton.setText("Príchod");
        prichodButton.setEnabled(false);
        prichodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prichodButtonActionPerformed(evt);
            }
        });

        kreditLabel.setText("Kredit: ");

        cisloKartyLabel.setText("Číslo permanentky: ");

        zadatCisloLabel.setText("Číslo permanentky: ");

        nacitatButton.setText("Načítať");
        nacitatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacitatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(klucLabel)
                    .addComponent(kreditLabel)
                    .addComponent(menoLabel)
                    .addComponent(cisloKartyLabel)
                    .addComponent(zadatCisloLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(zobrazMenoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(klucComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prichodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(zobrazCisloKartyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zobrazKreditLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cisloKartyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nacitatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cisloKartyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zadatCisloLabel)
                    .addComponent(nacitatButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(zobrazMenoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zobrazCisloKartyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cisloKartyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kreditLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zobrazKreditLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(klucLabel)
                    .addComponent(klucComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prichodButton))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prichodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prichodButtonActionPerformed
        if (zakaznik.isPritomny()) {
            JOptionPane.showMessageDialog(this, "Zákazník je už prítomný!");
        } else {
            Kluc kluc = (Kluc) klucComboBox.getSelectedItem();
            try {
                zakaznikManager.prichodKartouZakaznika(zakaznik, kluc);
            } catch (NedostatocnyKreditException e) {
                JOptionPane.showMessageDialog(this, "Nedostatočný kredit!");
            }
            dispose();
        }

    }//GEN-LAST:event_prichodButtonActionPerformed

    private void nacitatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacitatButtonActionPerformed
        try {
            zakaznik = zakaznikManager.dajZakaznikaSCislomPermanentky(cisloKartyTextField.getText());
            odblokovatPrichod();
        } catch (NeexistujuciZakaznikException e) {
            zablokovatPrichod();
            JOptionPane.showMessageDialog(this, "Neplatné číslo permanentky!");
        }

    }//GEN-LAST:event_nacitatButtonActionPerformed

    private void odblokovatPrichod() {
        klucComboBox.setEnabled(true);
        prichodButton.setEnabled(true);
        zobrazMenoLabel.setText(zakaznik.getMeno());
        zobrazKreditLabel.setText("" + zakaznik.getKredit());
        zobrazCisloKartyLabel.setText(zakaznik.getCisloPermanentky());
    }

    private void zablokovatPrichod() {
        klucComboBox.setEnabled(false);
        prichodButton.setEnabled(false);
        zobrazMenoLabel.setText("");
        zobrazKreditLabel.setText("");
        zobrazCisloKartyLabel.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cisloKartyLabel;
    private javax.swing.JTextField cisloKartyTextField;
    private javax.swing.JComboBox<Kluc> klucComboBox;
    private javax.swing.JLabel klucLabel;
    private javax.swing.JLabel kreditLabel;
    private javax.swing.JLabel menoLabel;
    private javax.swing.JButton nacitatButton;
    private javax.swing.JButton prichodButton;
    private javax.swing.JLabel zadatCisloLabel;
    private javax.swing.JLabel zobrazCisloKartyLabel;
    private javax.swing.JLabel zobrazKreditLabel;
    private javax.swing.JLabel zobrazMenoLabel;
    // End of variables declaration//GEN-END:variables
}
