package sk.upjs.ics.paz1c.fitnesscentrum.form;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import sk.upjs.ics.paz1c.fitnesscentrum.ObjectFactory;
import sk.upjs.ics.paz1c.fitnesscentrum.dao.RecepcnyDao;
import sk.upjs.ics.paz1c.fitnesscentrum.entity.Recepcny;
import sk.upjs.ics.paz1c.fitnesscentrum.manager.HesloManager;

public class PrihlasovanieForm extends javax.swing.JFrame {

    private final RecepcnyDao recepcnyDao = ObjectFactory.INSTANCE.getRecepcnyDao();
    private final HesloManager hesloManager = ObjectFactory.INSTANCE.getHesloManager();

    /**
     * Creates new form PrihlasovanieForm
     */
    public PrihlasovanieForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginTextField = new javax.swing.JTextField();
        loginLabel = new javax.swing.JLabel();
        hesloLabel = new javax.swing.JLabel();
        prihlasitButton = new javax.swing.JButton();
        hesloPasswordField = new javax.swing.JPasswordField();
        prihlasovanieMenuBar = new javax.swing.JMenuBar();
        novyRecepcny = new javax.swing.JMenu();
        nastavenia = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prihlásenie");
        setName("prihlasenieFrame"); // NOI18N
        setResizable(false);

        loginLabel.setText("Login:");

        hesloLabel.setText("Heslo:");

        prihlasitButton.setText("Prihlásiť");
        prihlasitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prihlasitButtonActionPerformed(evt);
            }
        });

        novyRecepcny.setText("Nový recepčný");
        novyRecepcny.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                novyRecepcnyMousePressed(evt);
            }
        });
        novyRecepcny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novyRecepcnyActionPerformed(evt);
            }
        });
        prihlasovanieMenuBar.add(novyRecepcny);

        nastavenia.setText("Nastavenia");
        nastavenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nastaveniaMousePressed(evt);
            }
        });
        prihlasovanieMenuBar.add(nastavenia);

        setJMenuBar(prihlasovanieMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hesloLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(hesloPasswordField))
                .addGap(18, 18, 18)
                .addComponent(prihlasitButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hesloLabel)
                    .addComponent(hesloPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prihlasitButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prihlasitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prihlasitButtonActionPerformed
        String heslo = hesloPasswordField.getText();
        String login = loginTextField.getText();
        Recepcny recepcny = recepcnyDao.dajRecepcneho(login);

        // funkcne prihlasovanie s databazou
         if (recepcny != null) {
            if (hesloManager.overHeslo(recepcny.getSalt(), heslo, recepcny.getId())) {
                new HlavneOknoForm(recepcny).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Zadané heslo nie je správne!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Recepčný so zadaným loginom neexistuje!");
        }
     /*   
        if ((recepcny != null)) {
            new HlavneOknoForm(recepcny).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Nesprávne prihlasovacie údaje!");
        }*/
    }//GEN-LAST:event_prihlasitButtonActionPerformed

    private void nastaveniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nastaveniaMousePressed
        new OverenieHeslaForm(this, true, "nastavenia").setVisible(true);
    }//GEN-LAST:event_nastaveniaMousePressed

    private void novyRecepcnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novyRecepcnyActionPerformed
        new NovyRecepcnyForm(this, true).setVisible(true);
    }//GEN-LAST:event_novyRecepcnyActionPerformed

    private void novyRecepcnyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novyRecepcnyMousePressed
        new OverenieHeslaForm(this, true, "novyRecepcny").setVisible(true);
    }//GEN-LAST:event_novyRecepcnyMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrihlasovanieForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrihlasovanieForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrihlasovanieForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrihlasovanieForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new PrihlasovanieForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hesloLabel;
    private javax.swing.JPasswordField hesloPasswordField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JMenu nastavenia;
    private javax.swing.JMenu novyRecepcny;
    private javax.swing.JButton prihlasitButton;
    private javax.swing.JMenuBar prihlasovanieMenuBar;
    // End of variables declaration//GEN-END:variables
}
