/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.fitnesscentrum.form;

import java.time.format.DateTimeFormatter;
import sk.upjs.ics.paz1c.fitnesscentrum.ObjectFactory;
import sk.upjs.ics.paz1c.fitnesscentrum.entity.Zakaznik;
import sk.upjs.ics.paz1c.fitnesscentrum.manager.ZakaznikManager;
import sk.upjs.ics.paz1c.fitnesscentrum.manager.impl.ZakaznikInfoManager;
import sk.upjs.ics.paz1c.fitnesscentrum.model.NavstevaTableModel;

/**
 *
 * @author dyske
 */
public class ZakaznikInfoForm extends javax.swing.JDialog {

    private final ZakaznikManager zakaznikManager = ObjectFactory.INSTANCE.getZakaznikManager();
    private final ZakaznikInfoManager zakaznikInfoManager = ObjectFactory.INSTANCE.getZakaznikInfoManager();
    private final Zakaznik zakaznik;
    
    /**
     * Creates new form ZakaznikInfoForm
     */
    public ZakaznikInfoForm(java.awt.Frame parent, boolean modal, Zakaznik zakaznik) {
        super(parent, modal);
        this.zakaznik = zakaznik;
        initComponents();
        postInitComponents();
    }
    
    private void postInitComponents() {
        kreditDataLabel.setText(((Double)zakaznik.getKredit()).toString());
        prichodDataLabel.setText(zakaznik.getPoslednyPrichod().format(DateTimeFormatter.ISO_DATE));
        menoDataLabel.setText(zakaznik.getMeno());

        oblubeneDataLabel.setText(zakaznikInfoManager.getOblubeneCvicenie(zakaznik));
        cviceniaDataLabel.setText(zakaznikInfoManager.getPocetCviceni(zakaznik).toString());
        kreditCelkomDataLabel.setText(zakaznikInfoManager.getKreditCelkom(zakaznik).toString());
        casDataLabel.setText(zakaznikInfoManager.getCelkovyCas(zakaznik).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoLabel = new javax.swing.JLabel();
        menoLabel = new javax.swing.JLabel();
        prichodLabel = new javax.swing.JLabel();
        kreditDataLabel = new javax.swing.JLabel();
        kreditLabel = new javax.swing.JLabel();
        prichodDataLabel = new javax.swing.JLabel();
        menoDataLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        navstevyTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        casLabel = new javax.swing.JLabel();
        casDataLabel = new javax.swing.JLabel();
        kreditCelkomDataLabel = new javax.swing.JLabel();
        kreditCelkomLabel = new javax.swing.JLabel();
        cviceniaLabel = new javax.swing.JLabel();
        cviceniaDataLabel = new javax.swing.JLabel();
        oblubeneLabel = new javax.swing.JLabel();
        oblubeneDataLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        infoLabel.setText("Informácie o zákazníkovi:");

        menoLabel.setText("Meno:");

        prichodLabel.setText("Posledný príchod:");

        kreditDataLabel.setText("30 EUR");

        kreditLabel.setText("Kredit:");

        prichodDataLabel.setText("23. 2. 2017, 18:43");

        menoDataLabel.setText("Jan Hrach");

        navstevyTable.setModel(new NavstevaTableModel(zakaznik));
        jScrollPane1.setViewportView(navstevyTable);

        casLabel.setText("Celkový čas:");

        casDataLabel.setText("117 minút");

        kreditCelkomDataLabel.setText("2000 EUR");

        kreditCelkomLabel.setText("Kredit celkom:");

        cviceniaLabel.setText("Počet cvičení:");

        cviceniaDataLabel.setText("99");

        oblubeneLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        oblubeneLabel.setText("Obľúbené:");

        oblubeneDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        oblubeneDataLabel.setText("Aerobic");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(menoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menoDataLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(prichodLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prichodDataLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kreditLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kreditDataLabel)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(casLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(casDataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(infoLabel)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cviceniaLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cviceniaDataLabel)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kreditCelkomLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kreditCelkomDataLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(oblubeneLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(oblubeneDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jSeparator2))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menoLabel)
                    .addComponent(menoDataLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prichodLabel)
                    .addComponent(kreditDataLabel)
                    .addComponent(kreditLabel)
                    .addComponent(prichodDataLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casLabel)
                    .addComponent(casDataLabel)
                    .addComponent(kreditCelkomDataLabel)
                    .addComponent(kreditCelkomLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cviceniaLabel)
                    .addComponent(cviceniaDataLabel)
                    .addComponent(oblubeneLabel)
                    .addComponent(oblubeneDataLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel casDataLabel;
    private javax.swing.JLabel casLabel;
    private javax.swing.JLabel cviceniaDataLabel;
    private javax.swing.JLabel cviceniaLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel kreditCelkomDataLabel;
    private javax.swing.JLabel kreditCelkomLabel;
    private javax.swing.JLabel kreditDataLabel;
    private javax.swing.JLabel kreditLabel;
    private javax.swing.JLabel menoDataLabel;
    private javax.swing.JLabel menoLabel;
    private javax.swing.JTable navstevyTable;
    private javax.swing.JLabel oblubeneDataLabel;
    private javax.swing.JLabel oblubeneLabel;
    private javax.swing.JLabel prichodDataLabel;
    private javax.swing.JLabel prichodLabel;
    // End of variables declaration//GEN-END:variables
}
