package sk.upjs.ics.paz1c.fitnesscentrum.form;

import javax.swing.JOptionPane;
import sk.upjs.ics.paz1c.fitnesscentrum.DaoFactory;
import sk.upjs.ics.paz1c.fitnesscentrum.Hashovanie;
import sk.upjs.ics.paz1c.fitnesscentrum.dao.RecepcnyDao;
import sk.upjs.ics.paz1c.fitnesscentrum.entity.Recepcny;

public class ZmenaHeslaRecepcnehoForm extends javax.swing.JDialog {

    private Recepcny recepcny;
    private final RecepcnyDao recepcnyDao;

    /**
     * Creates new form ZmenaHeslaRecepcnehoJDialog
     */
    public ZmenaHeslaRecepcnehoForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        recepcnyDao = DaoFactory.INSTANCE.getRecepcnyDao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noveHesloZnovaLabel = new javax.swing.JLabel();
        stareHesloPasswordField = new javax.swing.JPasswordField();
        noveHesloPasswordField = new javax.swing.JPasswordField();
        noveHesloZnovaPasswordField = new javax.swing.JPasswordField();
        loginTextField = new javax.swing.JTextField();
        ulozZmenyButton = new javax.swing.JButton();
        zrusitButton = new javax.swing.JButton();
        loginjLabel = new javax.swing.JLabel();
        stareHesloLabel = new javax.swing.JLabel();
        noveHesloLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zmena hesla recepčného");

        noveHesloZnovaLabel.setText("Nové heslo znova:");

        ulozZmenyButton.setText("Ulož zmeny");
        ulozZmenyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulozZmenyButtonActionPerformed(evt);
            }
        });

        zrusitButton.setText("Zrušiť");
        zrusitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zrusitButtonActionPerformed(evt);
            }
        });

        loginjLabel.setText("Login:");

        stareHesloLabel.setText("Staré heslo:");

        noveHesloLabel.setText("Nové heslo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginjLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stareHesloLabel)
                                    .addComponent(noveHesloLabel))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stareHesloPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noveHesloPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(noveHesloZnovaLabel)
                                .addGap(18, 18, 18)
                                .addComponent(noveHesloZnovaPasswordField))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ulozZmenyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(zrusitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginjLabel)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stareHesloLabel)
                    .addComponent(stareHesloPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noveHesloLabel)
                    .addComponent(noveHesloPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noveHesloZnovaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noveHesloZnovaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ulozZmenyButton)
                    .addComponent(zrusitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ulozZmenyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulozZmenyButtonActionPerformed
        String login = loginTextField.getText();
        String heslo = stareHesloPasswordField.getText();
        recepcny = recepcnyDao.dajRecepcneho(login);

        if (recepcny != null && login.equals(recepcny.getLogin())) {
            String hashovaneHeslo = Hashovanie.zahesuj(recepcny.getSalt(), heslo);
            if (hashovaneHeslo.equals(recepcny.getHeslo())) {
                noveHesloPasswordField.enable(true);
                noveHesloZnovaPasswordField.enable(true);

                String noveHashovaneHeslo = Hashovanie.zahesuj(recepcny.getSalt(), noveHesloPasswordField.getText());
                String noveHashovaneHesloZnova = Hashovanie.zahesuj(recepcny.getSalt(), noveHesloZnovaPasswordField.getText());

                if (!("").equals(noveHesloPasswordField.getText())) {
                    if (noveHashovaneHeslo.equals(noveHashovaneHesloZnova)) {
                        recepcny.setHeslo(noveHashovaneHeslo);
                        DaoFactory.INSTANCE.getRecepcnyDao().updateRecepcneho(recepcny);
                        JOptionPane.showMessageDialog(this, "Heslo recepčného s loginom " + recepcny.getLogin() + " bolo zmenené!");
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Nové heslo sa nezhoduje.");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Nové heslo nemôže byť prázdne.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nesprávne heslo");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Recepčný s daným loginom neexistuje");
        }
    }//GEN-LAST:event_ulozZmenyButtonActionPerformed

    private void zrusitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zrusitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_zrusitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZmenaHeslaRecepcnehoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZmenaHeslaRecepcnehoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZmenaHeslaRecepcnehoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZmenaHeslaRecepcnehoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ZmenaHeslaRecepcnehoForm dialog = new ZmenaHeslaRecepcnehoForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField loginTextField;
    private javax.swing.JLabel loginjLabel;
    private javax.swing.JLabel noveHesloLabel;
    private javax.swing.JPasswordField noveHesloPasswordField;
    private javax.swing.JLabel noveHesloZnovaLabel;
    private javax.swing.JPasswordField noveHesloZnovaPasswordField;
    private javax.swing.JLabel stareHesloLabel;
    private javax.swing.JPasswordField stareHesloPasswordField;
    private javax.swing.JButton ulozZmenyButton;
    private javax.swing.JButton zrusitButton;
    // End of variables declaration//GEN-END:variables
}
