package sk.upjs.ics.paz1c.fitnesscentrum.form;

import javax.swing.JOptionPane;
import sk.upjs.ics.paz1c.fitnesscentrum.ObjectFactory;
import sk.upjs.ics.paz1c.fitnesscentrum.entity.Zakaznik;
import sk.upjs.ics.paz1c.fitnesscentrum.exception.PritomnyZakaznikException;
import sk.upjs.ics.paz1c.fitnesscentrum.manager.ZakaznikManager;
import sk.upjs.ics.paz1c.fitnesscentrum.model.ZakaznikTableModel;

public class ZoznamZakaznikovForm extends javax.swing.JDialog {

    private final ZakaznikManager zakaznikManager = ObjectFactory.INSTANCE.getZakaznikManager();
    private static final int ID_COLUMN = 5;
    
    /**
     * Creates new form ZoznamZakaznikovForm
     */
    public ZoznamZakaznikovForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zoznamZakaznikovScrollPane = new javax.swing.JScrollPane();
        zoznamZakaznikovTable = new javax.swing.JTable();
        zmazatButton = new javax.swing.JButton();
        hladatPodlaMenaLabel = new javax.swing.JLabel();
        hladatPodlaMenaTextField = new javax.swing.JTextField();
        hladatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zoznam zákazníkov");

        zoznamZakaznikovTable.setModel(new ZakaznikTableModel(""));
        zoznamZakaznikovScrollPane.setViewportView(zoznamZakaznikovTable);

        zmazatButton.setText("Zmazať");
        zmazatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmazatButtonActionPerformed(evt);
            }
        });

        hladatPodlaMenaLabel.setText("Hľadať podľa mena: ");

        hladatButton.setText("Hľadať");
        hladatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hladatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hladatPodlaMenaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hladatPodlaMenaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hladatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zmazatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(zoznamZakaznikovScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hladatPodlaMenaLabel)
                    .addComponent(hladatButton)
                    .addComponent(zmazatButton)
                    .addComponent(hladatPodlaMenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zoznamZakaznikovScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void zmazatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmazatButtonActionPerformed
        try {
            Long idZakaznika = (Long) zoznamZakaznikovTable.getModel().getValueAt(this.zoznamZakaznikovTable.getSelectedRow(), ID_COLUMN);
            Zakaznik zakaznik = zakaznikManager.dajZakaznikaSId(idZakaznika);
            Object[] options = {"Zmazať", "Zrušiť"};
            if (JOptionPane.showOptionDialog(this, "Chcete zmazať zákazníka "
                    + zakaznik.getMeno() + "?", "Zmazať zákazníka",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                    options, options[0]) == JOptionPane.YES_OPTION) {
                zakaznikManager.zmazZakaznika(zakaznik);
                aktualizovatZoznamZakaznikov();
            }
        } catch (PritomnyZakaznikException e) {
            JOptionPane.showMessageDialog(this, "Nemožno vymazať prítomného zákazníka!");

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Vyber zákazníka na zmazanie!");
        }
    }//GEN-LAST:event_zmazatButtonActionPerformed

    private void hladatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hladatButtonActionPerformed
        zoznamZakaznikovTable.setModel(new ZakaznikTableModel(hladatPodlaMenaTextField.getText()));
        aktualizovatZoznamZakaznikov();
    }//GEN-LAST:event_hladatButtonActionPerformed

    public void aktualizovatZoznamZakaznikov() {
        ZakaznikTableModel model = (ZakaznikTableModel) zoznamZakaznikovTable.getModel();
        model.aktualizovat();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hladatButton;
    private javax.swing.JLabel hladatPodlaMenaLabel;
    private javax.swing.JTextField hladatPodlaMenaTextField;
    private javax.swing.JButton zmazatButton;
    private javax.swing.JScrollPane zoznamZakaznikovScrollPane;
    private javax.swing.JTable zoznamZakaznikovTable;
    // End of variables declaration//GEN-END:variables
}
