package sk.upjs.ics.paz1c.fitnesscentrum.form;

import javax.swing.JOptionPane;
import sk.upjs.ics.paz1c.fitnesscentrum.DaoFactory;
import sk.upjs.ics.paz1c.fitnesscentrum.SpinningTableModel;
import sk.upjs.ics.paz1c.fitnesscentrum.dao.SpinningDao;
import sk.upjs.ics.paz1c.fitnesscentrum.entity.Spinning;

public class ZrusSpinningForm extends javax.swing.JDialog {

    private static int ID_COLUMN = 2;
    private Spinning spinning;
    private SpinningDao spinningDao;

    /**
     * Creates new form ZrusSpinningForm
     */
    public ZrusSpinningForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        spinningDao = DaoFactory.INSTANCE.getSpinningDao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zoznamSpinningovScrollPane = new javax.swing.JScrollPane();
        zoznamSpinningovTable = new javax.swing.JTable();
        zrusSpinningButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zruš spinning");

        zoznamSpinningovTable.setModel(new SpinningTableModel());
        zoznamSpinningovScrollPane.setViewportView(zoznamSpinningovTable);

        zrusSpinningButton.setText("Zruš spinning");
        zrusSpinningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zrusSpinningButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(287, Short.MAX_VALUE)
                .addComponent(zrusSpinningButton)
                .addContainerGap())
            .addComponent(zoznamSpinningovScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(zoznamSpinningovScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(zrusSpinningButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zrusSpinningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zrusSpinningButtonActionPerformed
        try {
            Long idSpinningu = (Long) zoznamSpinningovTable.getModel().getValueAt(this.zoznamSpinningovTable.getSelectedRow(), ID_COLUMN);
            spinning = spinningDao.dajSpinningSId(idSpinningu);

            Object[] options = {"Zmazať", "Zrušiť"};
            if (JOptionPane.showOptionDialog(this, "Naozaj chcete zmazať spinning s instruktorom " + spinning.getInstruktor() + ", ktorý sa má uskutočniť dňa " + spinning.getDatum().toLocalDate() + " o " + spinning.getDatum().toLocalTime() + "?", "Zmaž kľúč", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[1]) == 1) {
                return;
            }
            spinningDao.vymazSpinning(idSpinningu);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nie je vybraný žiaden spinning.");
        }
        aktualizujZoznamSpinningovTable();
    }//GEN-LAST:event_zrusSpinningButtonActionPerformed

    private void aktualizujZoznamSpinningovTable() {
        SpinningTableModel model = (SpinningTableModel) zoznamSpinningovTable.getModel();
        model.aktualizovat();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZrusSpinningForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZrusSpinningForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZrusSpinningForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZrusSpinningForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ZrusSpinningForm dialog = new ZrusSpinningForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane zoznamSpinningovScrollPane;
    private javax.swing.JTable zoznamSpinningovTable;
    private javax.swing.JButton zrusSpinningButton;
    // End of variables declaration//GEN-END:variables
}
